pub mod app;
pub mod buffer;
pub mod editor;
pub mod tuinix_ext;
// pub mod widget_console;
// pub mod widget_dialog;
// pub mod widget_editor;
// pub mod widget_notification;
// pub mod widget_status;
// pub mod widget_text;
